
//------------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by the T4 template 'FontAsset.tt'
//
//     This file will automatically update on new builds and when new font files
//	   are added to the corrosponding assets folder.
//
//	   To manually regenerate the file go to 'Build > Transform all T4 Templates'.
// </auto-generated>
//------------------------------------------------------------------------------------

namespace JustStatics.Droid.Shared.AssetsFactories
{
    public enum FontAsset
	{
		harlow_solid_italic
	}
}
