
//------------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by the T4 template 'GradientAsset.tt'
//
//     This file will automatically update on new builds and when new gradient files
//	   are added to the corrosponding assets folder.
//
//	   To manually regenerate the file go to 'Build > Transform all T4 Templates'.
// </auto-generated>
//------------------------------------------------------------------------------------

namespace JustStatics.Droid.Shared.AssetsFactories
{
    public enum GradientAsset
	{
		grad_mean_fruit
	}
}
